name: Create Build Image

on:
  schedule:
    - cron: '0 4 * * 2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        env:
          DOCKER_USERNAME: token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_BUILDKIT: 1
        run: scripts/create-build-image.sh
